ep_mobile/src/objects/PRMConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>PRM Go! configurations</description>
    <fields>
        <fullName>EmailNotifyDomain__c</fullName>
        <description>This field will be used in PRM Go! App to restrict the email domains. If the value is set to &quot;All&quot;, this will allow to send   emails to users(Salesforce or non Salesforce).</description>
        <inlineHelpText>Enter the domain names with comma(,) separated values (e.g. evariant.com,google.com).</inlineHelpText>
        <label>Email Notify Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PRM Config</label>
</CustomObject>

ep_mobile/src/classes/RestPrmPostInstallConfigurations.cls
/* Copyright (c) 2008-2014 Evariant */
global class RestPrmPostInstallConfigurations implements InstallHandler {
	
	global void onInstall(InstallContext context) {
		String nsPrefix = uString.Empty;
		String soql = uString.Empty;
        String filedName = 'EmailNotifyDomain__c';
        String objectName =  'PRMConfig__c';
        
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        sObject config = null;
        List<sObject> configs = new List<sObject>(); 
        for(Schema.SObjectType typeof: gd.values()){
        	String sTemp = String.valueOf(typeof);
        	if(sTemp.toLowerCase() == 'hc4m__prmconfig__c'){ 
	        	nsPrefix = 'HC4M';
	        	break;                
	        }
        }        
        if(!String.isBlank(nsPrefix)){
        	filedName = nsPrefix + '__'  + filedName;
        	objectName = nsPrefix + '__'  + objectName; 
        }
                 
        soql += 'SELECT Name, ' + filedName + ' From ' + objectName; 
        System.debug(LoggingLevel.ERROR, soql);
        
        configs = Database.query(soql);
        
        if(configs.isEmpty() || Test.isRunningTest()){ //Check if Config record exist?, if not create PRM Go! record
        	config = Schema.getGlobalDescribe().get(objectName).newSObject();
        	config.put('Name', 'NotifyEmailDomain');
        	config.put(filedName, 'All');        	
        	insert config; 
        	System.debug(LoggingLevel.ERROR, 'PRMGo!>>Custom Setting created.');
        }
        
	}	
}